[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "road_to_waffle_house"
version = "0.1.1"
description = "Find your way to the nearest Waffle House using Google Maps"
authors = [{ name="Bear, Justin, Ryan, Joe", email="jbrigg17@emich.edu" }]
readme = "README.md"
license = { file="LICENSE" }
dependencies = [
    "requests",
    "pygame",
    "tkinter; sys_platform == 'win32'",
]
requires-python = ">=3.7"

[project.urls]
Homepage = "https://github.com/yourusername/road_to_waffle_house"

[tool.hatch.build.targets.wheel]
packages = ["road_to_waffle_house"]